FROM golang:1.22-alpine
WORKDIR /app
COPY go.mod main.go ./
#RUN go mod download
RUN echo "Mostrando archivos en /app:" && ls -la /app
RUN go build -o /ms-adapter-tranfer-user
CMD ["/ms-adapter-tranfer-user"]