name: Despliegue API Go en GKE

on:
  push:
    branches:
      - main
env:
    PROJECT_ID: digital-nation
    IMAGE_NAME: ms-adapter-transfer-user
    REGION: us-central1
      

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Docker Build
      run: docker build ./

    - name: Authenticate to Google Cloud
      uses: 'google-github-actions/auth@v0.6.0'
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}
        token_format: 'access_token'

    - name: Docker Push
      run: docker push https://us-central1-go.pkg.dev/endless-gamma-415720/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:latest

    - name: Artifact Registry Import
      run: |
        gcloud artifacts repositories docker import \
          gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:latest \
          --repository=${{ env.IMAGE_NAME }} \
          --location=${{ env.REGION }}

